import discord
authorusername= ""

def handle_response(message) -> str:
    p_message = message.lower()
    print("responses.py says username is " + authorusername)
    if 'gun' in p_message:
        return 'Murica!'
    if 'play' in p_message and 'football' in p_message and authorusername == 'moroccandudelmao':
        return 'Its soccer, you Moroccan!'
    if p_message == 'make fun of morocco, robodog.' and authorusername == 'thedog51gamer':
        return "Oh, for fuck's sake, talking about Moroccan, the gaming genius from the land of dust and camels. This dude thinks he's the Sultan of the joystick, but in reality, he's just a sorry excuse for a gamer. I mean, seriously, Morocco, the land of vibrant culture and historic cities, and this moron is the best they can offer in the gaming department? What a fucking embarrassment. First off, let's talk about his skills – or lack thereof. It's like watching a blindfolded toddler trying to find its way through a maze. I've seen potatoes with more strategic thinking than this numbnut. And don't even get me started on his reflexes; they're slower than a snail on tranquilizers. Maybe he's too busy riding his fucking camel to bother improving. Now, the name – Moroccan. Real creative, buddy. Did your brain freeze in the Sahara heat, or are you just too unimaginative to come up with something remotely interesting? I bet his creativity level is on par with a dead fish. 'Moroccan,' really? Might as well call yourself 'Bland-african' for all the excitement your presence brings. And his online demeanor? Holy shit, it's like dealing with a hormonal teenager who just discovered the internet. Every sentence he types is a painful reminder of why some people should never be allowed near a keyboard. I'd rather listen to nails on a chalkboard than endure his inane chatter. So, Robodog, making fun of Moroccan is like shooting fish in a barrel. The guy is a walking, talking joke. I wouldn't be surprised if he thinks the Casablanca movie is a documentary about his epic gaming journey. Get your shit together, Moroccan, or better yet, stick to something you're good at.. like counting grains of sand in the Sahara."
    if p_message == 'make fun of gingers, robodog.':
        return "I fucking hate gingers. They just look so revoltingly bad every time i see such a color of hair, i flinch. But why, why do they look so bad? That is probably your question right now. I’ll explain that to you. First we start with the horrible light color of their skin. I get that you’re white, but you look like a vampire. Every time the sun shines, it actually bounces off your skin like a mirror. Every time i look at their skin color i get temporatily blinded. The color of the gingers’ skin is so bright it gives off radiation. It’s so unbelievably white that racists start to like the blacks just to become racists to you. Gingers’ skin color is so light that it absorbs all the light from the sun to become the sun themselves. Now that i’m done with their skin color, let’s start with their choice of clothing. Every thing the gingers wear looks like clothing knit by their grandmother. The ugly christmas sweaters look way better than what gingers wear. You could put a piece of GAY FURRY ART on your shirt and it would still manage to look better than what gingers wear. The choice of clothing is probably not as bad as their stupid freckles. Having freckles is fine, but just having red hair already makes having freckles way worse. The freckles stand out so much on their bright skin that it makes it impossible to look away. The freckles are so obvious and gigantic that they look like tumors. The freckles are so dark that the blackest color on earth can never be as dark as the freckles of gingers. I’m done with the freckles, so let’s start with the hair. Gingers’ hair looks so bad that if you even see a red hair laying around, it makes you puke. Their hair is so thin too that you can look through it and see their sculp. Their hair color is so weird that scientists think it’s a new color. No wonder that gingers get bullied."